from .model import (
    Axis,
    BoundaryIndex,
    BoundingBoxLabel,
    BoundingBox,
    Bounds3D,
    CornerId,
    FaceId,
    Projection2D,
    Shape3D,
    VoxelIndex,
)
from .manager import BoundingBoxChange, BoundingBoxManager, ChangeKind
from .io import (
    FORMAT_MAGIC,
    FORMAT_VERSION,
    HEADER_LINE,
    BoundingBoxFileData,
    load_bounding_boxes,
    parse_bounding_boxes_text,
    save_bounding_boxes,
    serialize_bounding_boxes,
)
from .projection import (
    ProjectedBoundingBox2D,
    project_box_to_slice,
    project_boxes_to_slice,
)
from .interaction import (
    BoundingBoxHandleHit,
    CornerHandle,
    EdgeHandle,
    FaceUpdate,
    HandleKind,
    HandleName,
    face_updates_for_handle_drag,
    hit_test_projected_box_handles,
    translation_delta_for_edge_drag,
)

__all__ = [
    "Axis",
    "BoundaryIndex",
    "BoundingBoxLabel",
    "BoundingBox",
    "Bounds3D",
    "CornerId",
    "FaceId",
    "Projection2D",
    "Shape3D",
    "VoxelIndex",
    "ChangeKind",
    "BoundingBoxChange",
    "BoundingBoxManager",
    "FORMAT_MAGIC",
    "FORMAT_VERSION",
    "HEADER_LINE",
    "BoundingBoxFileData",
    "load_bounding_boxes",
    "parse_bounding_boxes_text",
    "save_bounding_boxes",
    "serialize_bounding_boxes",
    "ProjectedBoundingBox2D",
    "project_box_to_slice",
    "project_boxes_to_slice",
    "EdgeHandle",
    "CornerHandle",
    "HandleName",
    "HandleKind",
    "FaceUpdate",
    "BoundingBoxHandleHit",
    "hit_test_projected_box_handles",
    "face_updates_for_handle_drag",
    "translation_delta_for_edge_drag",
]
